changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 New Workflows
      labels:
        - new-workflow
        - workflow
    - title: ✨ Enhancements
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - maintenance
        - chore
        - dependencies
    - title: 🔐 Security
      labels:
        - security
    - title: Other Changes
      labels:
        - "*"
