name: Auto Release with Release Please

on:
  workflow_call:
    inputs:
      release-type:
        description: 'Release type (node, python, rust, simple, etc.)'
        required: false
        type: string
        default: 'simple'
      config-file:
        description: 'Path to release-please config file'
        required: false
        type: string
        default: 'release-please-config.json'
      manifest-file:
        description: 'Path to release-please manifest file'
        required: false
        type: string
        default: '.release-please-manifest.json'
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token for creating releases'
        required: false

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: ${{ inputs.release-type }}
          config-file: ${{ inputs.config-file }}
          manifest-file: ${{ inputs.manifest-file }}
          token: ${{ secrets.GITHUB_TOKEN || github.token }}
